# Generated by Django 3.0.7 on 2020-07-30 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('tags', models.CharField(choices=[('EN', 'Entertainment'), ('EN2', 'Entertaintment 2'), ('EN3', 'Entertaintment 3'), ('EN4', 'Entertaintment 4'), ('EN5', 'Entertaintment 5')], default='EN', max_length=3)),
                ('dislike', models.ManyToManyField(blank=True, related_name='disliked_user', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='liked_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
