# Generated by Django 2.2.6 on 2020-07-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.CharField(choices=[('EN', 'Entertainment')], default='EN', max_length=3),
        ),
    ]
