# Generated by Django 2.2.6 on 2020-07-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questions_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=models.CharField(choices=[('EN', 'Entertainment'), ('EN2', 'Entertaintment 2'), ('EN3', 'Entertaintment 3'), ('EN4', 'Entertaintment 4'), ('EN5', 'Entertaintment 5')], default='EN', max_length=3),
        ),
    ]
