# Generated by Django 3.0.3 on 2020-08-02 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20200731_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='tags',
        ),
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(choices=[('EN', 'Entertainment'), ('EN2', 'Entertaintment 2'), ('EN3', 'Entertaintment 3'), ('EN4', 'Entertaintment 4'), ('EN5', 'Entertaintment 5')], default='EN', max_length=3, related_name='user_tag', to=settings.AUTH_USER_MODEL),
        ),
    ]
