# Generated by Django 3.0.3 on 2020-08-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200802_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='tags',
        ),
        migrations.AddField(
            model_name='questions',
            name='tags',
            field=models.CharField(choices=[('EN', 'Entertainment'), ('EN2', 'Entertaintment 2'), ('EN3', 'Entertaintment 3'), ('EN4', 'Entertaintment 4'), ('EN5', 'Entertaintment 5')], default='EN', max_length=3),
        ),
    ]
