# Generated by Django 2.2.6 on 2020-07-27 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='dislike',
        ),
        migrations.AddField(
            model_name='answers',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='disliked_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='answers',
            name='like',
        ),
        migrations.AddField(
            model_name='answers',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
