# Generated by Django 3.0.7 on 2020-07-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20200714_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.TextField(default='Enter Your Answer Here!'),
        ),
    ]
