# Generated by Django 3.0.7 on 2020-07-19 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200720_0148'),
        ('answers', '0004_auto_20200717_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.AddField(
            model_name='answers',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Questions'),
        ),
        migrations.AddField(
            model_name='comment',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='answers.Answers'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
