# Generated by Django 3.0.7 on 2020-07-27 20:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import phonenumber_field.modelfields
import portfolio.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, default=datetime.datetime(2020, 7, 27, 20, 54, 32, 502641, tzinfo=utc), null=True)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('profession', models.TextField(blank=True, max_length=100, null=True)),
                ('softwear', models.TextField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('photography', models.ImageField(blank=True, null=True, upload_to='work_photos/', validators=[portfolio.validators.validate_image_file_extension])),
                ('music', models.FileField(blank=True, null=True, upload_to='work_music/', validators=[portfolio.validators.validate_music_file_extension])),
                ('video', models.FileField(blank=True, null=True, upload_to='work_video/', validators=[portfolio.validators.validate_video_file_extension])),
                ('awards', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('tags', models.CharField(choices=[('EN', 'Entertainment'), ('EN2', 'Entertaintment 2'), ('EN3', 'Entertaintment 3'), ('EN4', 'Entertaintment 4'), ('EN5', 'Entertaintment 5')], default='EN', max_length=3)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
