# Generated by Django 3.0.7 on 2020-08-04 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import portfolio.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(auto_now_add=True)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('profession', models.TextField(blank=True, max_length=100, null=True)),
                ('softwear', models.TextField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('photography', models.ImageField(blank=True, null=True, upload_to='work_photos/', validators=[portfolio.validators.validate_image_file_extension])),
                ('music', models.FileField(blank=True, null=True, upload_to='work_music/', validators=[portfolio.validators.validate_music_file_extension])),
                ('video', models.FileField(blank=True, null=True, upload_to='work_video/', validators=[portfolio.validators.validate_video_file_extension])),
                ('awards', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('saved_questions', models.ManyToManyField(blank=True, related_name='saved_questions', to='questions.Questions')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
