# Generated by Django 3.0.7 on 2020-07-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
