# Generated by Django 3.0.7 on 2020-07-09 13:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import portfolio.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_auto_20200708_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='awards',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 9, 19, 8, 11, 877744), null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='followers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='work_music/', validators=[portfolio.validators.validate_music_file_extension]),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='photography',
            field=models.ImageField(blank=True, null=True, upload_to='work_photos/', validators=[portfolio.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='profession',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='softwear',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='work_video/', validators=[portfolio.validators.validate_video_file_extension]),
        ),
    ]
