# Generated by Django 3.0.7 on 2020-07-29 11:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200728_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 29, 11, 37, 57, 396667, tzinfo=utc), null=True),
        ),
    ]
