# Generated by Django 3.0.7 on 2020-07-29 16:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200729_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 29, 16, 10, 7, 365146, tzinfo=utc), null=True),
        ),
    ]
