# Generated by Django 3.0.7 on 2020-07-30 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200729_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 30, 9, 21, 47, 474529, tzinfo=utc), null=True),
        ),
    ]
