# Generated by Django 3.0.7 on 2020-07-31 07:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200730_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 31, 7, 58, 35, 921120, tzinfo=utc), null=True),
        ),
    ]
