# Generated by Django 3.0.3 on 2020-07-30 17:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200730_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 30, 17, 58, 43, 619991, tzinfo=utc), null=True),
        ),
    ]
