# Generated by Django 3.0.3 on 2020-08-01 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200731_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 1, 14, 8, 54, 62065, tzinfo=utc), null=True),
        ),
    ]
