# Generated by Django 3.0.7 on 2020-07-10 12:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200710_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 12, 54, 57, 251499, tzinfo=utc), null=True),
        ),
    ]
