# Generated by Django 3.0.3 on 2020-08-02 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20200801_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 2, 7, 9, 53, 596588, tzinfo=utc), null=True),
        ),
    ]
