# Generated by Django 3.0.7 on 2020-07-10 21:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200711_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 10, 21, 40, 53, 615731, tzinfo=utc), null=True),
        ),
    ]
