# Generated by Django 3.0.7 on 2020-07-11 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20200711_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 11, 9, 18, 0, 648252, tzinfo=utc), null=True),
        ),
    ]
