# Generated by Django 3.0.3 on 2020-08-02 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20200802_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 8, 2, 9, 11, 30, 278579, tzinfo=utc), null=True),
        ),
    ]
