# Generated by Django 3.0.7 on 2020-07-12 07:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0016_auto_20200711_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='following',
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 12, 7, 36, 37, 508889, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
