# Generated by Django 3.0.7 on 2020-07-12 07:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0017_auto_20200712_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 12, 7, 56, 10, 736275, tzinfo=utc), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userprofilemodel',
            unique_together={('follower', 'following')},
        ),
    ]
