# Generated by Django 3.0.7 on 2020-07-12 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20200712_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 12, 9, 22, 40, 688201, tzinfo=utc), null=True),
        ),
    ]
