# Generated by Django 3.0.7 on 2020-07-14 12:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20200714_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 14, 12, 43, 51, 659442, tzinfo=utc), null=True),
        ),
    ]
