# Generated by Django 3.0.7 on 2020-07-15 16:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20200714_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 15, 16, 36, 15, 868999, tzinfo=utc), null=True),
        ),
    ]
