# Generated by Django 3.0.7 on 2020-07-17 04:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20200717_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 17, 4, 46, 18, 160050, tzinfo=utc), null=True),
        ),
    ]
