# Generated by Django 3.0.7 on 2020-07-19 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_auto_20200719_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 19, 19, 22, 32, 80101, tzinfo=utc), null=True),
        ),
    ]
