# Generated by Django 3.0.7 on 2020-07-19 20:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_auto_20200720_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 19, 20, 18, 43, 324676, tzinfo=utc), null=True),
        ),
    ]
