# Generated by Django 3.0.7 on 2020-07-21 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_auto_20200721_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 21, 13, 53, 46, 509726, tzinfo=utc), null=True),
        ),
    ]
