# Generated by Django 3.0.7 on 2020-07-23 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0041_auto_20200721_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 23, 14, 25, 49, 780079, tzinfo=utc), null=True),
        ),
    ]
