# Generated by Django 3.0.7 on 2020-07-23 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0042_auto_20200723_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 23, 15, 30, 16, 392796, tzinfo=utc), null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userprofilemodel',
            unique_together=set(),
        ),
    ]
