# Generated by Django 3.0.7 on 2020-07-23 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0043_auto_20200723_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 23, 16, 26, 3, 424289, tzinfo=utc), null=True),
        ),
    ]
