# Generated by Django 3.0.7 on 2020-07-26 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0045_auto_20200723_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 26, 7, 28, 17, 816596, tzinfo=utc), null=True),
        ),
    ]
