# Generated by Django 2.2.6 on 2020-07-27 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0045_auto_20200723_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 27, 12, 18, 50, 183375, tzinfo=utc), null=True),
        ),
    ]
