# Generated by Django 3.0.7 on 2020-07-26 07:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_auto_20200726_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 26, 7, 40, 11, 355874, tzinfo=utc), null=True),
        ),
    ]
