# Generated by Django 2.2.6 on 2020-07-27 16:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0051_auto_20200727_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 27, 16, 38, 12, 740145, tzinfo=utc), null=True),
        ),
    ]
