# Generated by Django 2.2.6 on 2020-07-27 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0052_auto_20200727_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='following',
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 7, 27, 16, 52, 26, 9335, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='tags',
            field=models.CharField(choices=[('EN', 'Entertainment'), ('EN2', 'Entertaintment 2'), ('EN3', 'Entertaintment 3'), ('EN4', 'Entertaintment 4'), ('EN5', 'Entertaintment 5')], default='EN', max_length=3),
        ),
    ]
